import type { Metadata } from "next";
import { Poppins, Nunito } from "next/font/google";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import Script from "next/script";
import { Theme } from "@radix-ui/themes";

const poppins = Poppins({
      weight: ["300", "400", "500", "700"],
      variable: "--font-poppins",
      subsets: ["latin"],
});

const nunito = Nunito({
      variable: "--font-nunito",
      subsets: ["latin"],
});

export const metadata: Metadata = {
      title: "Create Next App",
      description: "Generated by create next app",
};

export default function RootLayout({
      children,
}: Readonly<{
      children: React.ReactNode;
}>) {
      return (
            <html
                  lang="fr"
                  suppressHydrationWarning
                  className={`${poppins.variable} ${nunito.variable}`}>
                  <head>
                        {(process.env.NODE_ENV === "development" || process.env.VERCEL_ENV === "preview") && (
                              <Script src="https://unpkg.com/react-scan/dist/auto.global.js" />
                        )}
                  </head>
                  <body>
                        <Theme>
                              <main>{children}</main>
                        </Theme>
                  </body>
            </html>
      );
}
